import { ArrowRight, Check } from "lucide-react";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import PageHero from "@/components/PageHero";
import Seo from "@/components/Seo";

const process = [["01","Assess","Understand your goals, training history, environment, movement confidence, and current capability."],["02","Build","Create an individualized plan around the qualities and real-life demands that matter to you."],["03","Coach","Use feedback, accountability, adjustments, and education to make the plan work in real life."],["04","Reassess","Measure what changed, identify the next opportunity, and continue expanding your options."]];
const includes = ["Complete starting-point assessment","Individualized 12-week training plan","Movement demonstrations and coaching guidance","Regular progress reviews and program adjustments","Direct accountability and coach support","End-of-program reassessment and next-step plan"];

export default function Coaching(){return <div className="min-h-screen bg-black text-white"><Seo title="Online Fitness Coaching | ALLEIN" description="Personalized nervous-system-first online coaching for active adults who want lasting strength, mobility, balance, coordination, power, and confidence." path="/coaching" schema={{"@type":"Service",name:"ALLEIN Personalized Online Coaching",provider:{"@type":"Organization",name:"ALLEIN"},areaServed:"United States",serviceType:"Online fitness coaching"}}/><Navbar/><main id="main-content"><PageHero eyebrow="Personalized coaching" title={<>Build capability that <span className="text-gold-gradient">transfers to life.</span></>} intro="A 12-week coaching experience built around your body, your environment, and the physical qualities you want to preserve or reclaim."><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="https://tally.so/r/dWeQJz" className="inline-flex items-center justify-center gap-2 rounded-md bg-gold-gradient px-6 py-3.5 text-sm font-bold text-black">Apply for founding coaching <ArrowRight className="h-4 w-4"/></a><a href="https://allein.kit.com/b41a314882" className="inline-flex items-center justify-center rounded-md border border-white/15 px-6 py-3.5 text-sm font-semibold">Take the free self-check</a></div></PageHero>
<section className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl text-center"><span className="eyebrow">How it works</span><h2 className="section-title mt-5">Coaching that evolves with you.</h2></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{process.map(([n,t,d])=><article key={n} className="rounded-xl border border-white/[.08] bg-[#050505] p-6"><span className="font-[var(--font-display)] text-3xl font-bold text-[#D4AF37]">{n}</span><h3 className="mt-5 font-[var(--font-display)] text-2xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-relaxed text-[#888]">{d}</p></article>)}</div></div></section>
<section className="border-y border-[#D4AF37]/10 bg-[#050505] py-20 lg:py-24"><div className="mx-auto grid max-w-6xl gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:items-center lg:px-8"><div><span className="eyebrow">What is included</span><h2 className="section-title mt-5">More than a workout file.</h2><p className="mt-6 text-lg leading-relaxed text-[#999]">You receive a plan, but the coaching relationship is what helps that plan stay appropriate as your schedule, readiness, confidence, and capabilities change.</p></div><div className="space-y-3">{includes.map(item=><div key={item} className="flex gap-3 rounded-lg border border-white/[.07] bg-black p-4"><Check className="h-5 w-5 shrink-0 text-[#D4AF37]"/><span className="text-[#B0B0B0]">{item}</span></div>)}</div></div></section>
<section className="py-20 text-center lg:py-28"><div className="mx-auto max-w-3xl px-4"><span className="eyebrow">Founding coaching</span><h2 className="section-title mt-5">Ready to build a body you trust?</h2><p className="mt-6 text-lg leading-relaxed text-[#999]">Applying starts a conversation. It does not commit you to purchasing coaching.</p><a href="https://tally.so/r/dWeQJz" className="mt-8 inline-flex items-center gap-2 rounded-md bg-gold-gradient px-7 py-4 text-sm font-bold text-black">Start your application <ArrowRight className="h-4 w-4"/></a></div></section>
</main><Footer/></div>}
